version: '3.5'

services:
    mongodb:
        image: mongo:5.0 
        volumes:
            - mongodata:/data/db
        networks:
            - btvn_default
volumes:
    mongodata:
        name: btvn_mongodata
        external: true

networks:
    btvn_default:
        external: true 
