version: '3.5'

services:
    mongodb:
        # image: mongo:5.0 
        build: ./db
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: minhson
        #     MONGO_INITDB_ROOT_PASSWORD: minhson
        #     MONGO_INITDB_DATABASE: test_database
        networks:
            - sonbm_default
volumes:
    mongodata:
        name: sonbm_mongodata
        external: true

networks:
    sonbm_default:
        external: true 
