version: '3.5'

services:
    api:
        build: ./app
        volumes:
            - ./:/app
        working_dir: /app
        environment:
            - FLASK_APP=./app/api.py
        command: flask run --host=0.0.0.0
        ports: 
            - 5000:5000
        networks:
            - sonbm_default
volumes:
    mongodata:

networks:
    sonbm_default:
        external: true 
