---
- name: sonbm
  hosts: all
  become: true
  gather_facts: true
  roles:
    - common
    - db
    - web
    - api
    - monitor
- name: log
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - lb
    - logging

